group: travis_latest
dist: xenial
language: python
cache: pip
python:
- '2.7'
- '3.6'
- '3.7'
matrix:
  allow_failures:
  - python: nightly
  - python: pypy
  - python: pypy3
install:
- pip install flake8
before_script:
- flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude=./venv*
- flake8 . --count --max-complexity=44 --max-line-length=127 --ignore=W504,F403,F405,E126,E127,E402,W605
  --statistics --exclude=./gluon/gluoncv2/models/others,./pytorch/pytorchcv/models/others,./chainer_/chainercv2/models/others,./keras_/kerascv/models/others,./tensorflow_/tensorflowcv/models/others,./venv*
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
